name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: luacheck
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - name: run luacheck
      run: nix shell nixpkgs#luajit nixpkgs#luajitPackages.luacheck -c luacheck --no-cache .

  test:
    name: busted
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - name: run busted
      run: nix shell nixpkgs#luajit nixpkgs#luajitPackages.luacheck -c busted

  format:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-21.11
    - uses: workflow/nix-shell-action@v3
      with:
        packages: stylua
        script: |
          stylua --color always --check lua/
